apiVersion: v1
kind: Service
metadata:
  name: ontopia
spec:
  ports:
  - name: virtuoso
    port: 8890
    targetPort: 8890
    protocol: TCP
  - name: lode
    port: 9999
    targetPort: 9999
    protocol: TCP
  - name: lodview
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ontoPia
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ontopia-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ontoPia
    spec:
      containers:
        - name: virtuoso
          image: 10.98.74.120:5000/virtuoso:1.0.0-SNAPSHOT
          env:
            - name: SPARQL_UPDATE
              value: "true"
          ports:
            - containerPort: 8890
        - name: lode
          image: 10.98.74.120:5000/lode:1.0.0-SNAPSHOT
          ports:
            - containerPort: 9999
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
        - name: lodview
          image: 10.98.74.120:5000/lodview:1.0.0-SNAPSHOT
          resources:
            requests:
              memory: "2Gi"
            limits:
              memory: "2Gi"
      imagePullSecrets:
        - name: regsecret
